// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cszhsywrgjqjltueuwzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzemhzeXdyZ2pxamx0dWV1d3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzMwOTQsImV4cCI6MjA1OTUwOTA5NH0.VuCc80KhcoRS3JFHWU3kFbqMgUyoJaE-bd9hh0Nhc-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);